delta:device: cuda
delta:forward_model_params.extra_info_var_reg: 100
delta:logging/server_ip: 192.168.43.102
delta:logging/server_port: 41689
delta:seed: 3
device: cuda
forward_model_params.extra_info_var_reg: 100
image:
  color: red
  shape:
  - 64
  - 64
initialization_type: 1
logging:
  gdrive_storage_folder: https://drive.google.com/drive/u/0/folders/12_wdaaWk_bCRpEnbO5K8cEWiClDp_mtc
  output_csv:
    path: /home/nas/Documents/STAI-tuned/inputs/https:(slash)(slash)docs.google.com(slash)spreadsheets(slash)d(slash)1F9iW8REYZzpzA8lDEwPLcrCU52PCJgnKf9aUCHwNVnU(slash)/stuned_sockets.csv
    row_number: 6
    spreadsheet_url: https://docs.google.com/spreadsheets/d/1F9iW8REYZzpzA8lDEwPLcrCU52PCJgnKf9aUCHwNVnU/edit#gid=778549050
    worksheet_name: stuned_sockets
  server_ip: 192.168.43.102
  server_port: 41689
  use_tb: false
  use_wandb: false
  wandb:
    netrc_path: ~/.netrc
params:
  random_seed: 42
seed: 3
use_hardcoded_config: false
