
###################### From configs.py ######################
HARDCODED_CONFIG = \
    None
AUTOGEN_PREFIX = "autogenerated"
EXP_NAME_CONFIG_KEY = "experiment_name"
START_TIME_CONFIG_KEY = "start_time"
RUN_PATH_CONFIG_KEY = "current_run_folder"
TYPE_KEY = "type"
ANY_KEY = "any"
NESTED_CONFIG_KEY_SEPARATOR = '.'

###################### From logger.py ######################
# string style
PROGRESS_FREQUENCY = 0.01
INDENT = "    "

# tmp folder name
LOGGER_ARG_NAME = "logger"
CONTROL_PREFIX = "\033["
CONTROL_SUFFIX = "m"
CONTROL_SEPARATOR = ";"
DEFAULT_TEXT_STYLE = "0"
BOLD_TEXT_STYLE = "1"
BLACK_COLOR_CODE = "40"
RED_COLOR_CODE = "31"
GREEN_COLOR_CODE = "32"
BLUE_COLOR_CODE = "34"
PURPLE_COLOR_CODE = "35"
CYAN_COLOR_CODE = "36"
WHITE_COLOR_CODE = "37"
DEFAULT_EXPERIMENT = "unknown_experiment"
DEFAULT_NAME_PREFIX = "_"
LOG_PREFIX = "(log)"
INFO_PREFIX = "(info)"
ERROR_PREFIX = "(error)"
MAX_LINE_LENGTH = 80

# logger messages
SEPARATOR = "".join(["="] * MAX_LINE_LENGTH)
STATUS_CSV_COLUMN = "status"
RUN_FOLDER_CSV_COLUMN = "run_folder"
WALLTIME_COLUMN = "walltime"
FIRST_REPORT_TIME_COLUMN = "starttime"
LAST_REPORT_TIME_COLUMN = "endtime"
SUBMITTED_STATUS = "Submitted"
RUNNING_STATUS = "Running"
COMPLETED_STATUS = "Completed"
FAIL_STATUS = "Fail"
WHETHER_TO_RUN_COLUMN = "whether_to_run"
OUTPUT_CSV_KEY = "output_csv"
PATH_KEY = "path"
ROW_NUMBER_KEY = "row_number"  # starts with 0
GDRIVE_FOLDER_KEY = "gdrive_storage_folder"
STDOUT_KEY = "stdout"
STDERR_KEY = "stderr"

# wandb
WANDB_URL_COLUMN = "WandB url"
WANDB_QUIET = True
WANDB_INIT_RETRIES = 100
WANDB_SLEEP_BETWEEN_INIT_RETRIES = 60
PROJECT_KEY = "project"


