delta:exp_group_name: basic-demo
delta:exp_name: short sleep time
delta:image.color: white
delta:logging/server_ip: 192.168.178.21
delta:logging/server_port: 42143
delta:run_locally: true
exp_group_name: basic-demo
exp_name: short sleep time
fixed_params:
  image:
    color: red
    shape:
    - 64
    - 64
  initialization_type: 1
  params:
    random_seed: 42
image.color: white
logging:
  gdrive_storage_folder: https://drive.google.com/drive/u/0/folders/12_wdaaWk_bCRpEnbO5K8cEWiClDp_mtc
  output_csv:
    path: /home/nas/Documents/STAI-tuned/inputs/https:(slash)(slash)docs.google.com(slash)spreadsheets(slash)d(slash)1kzlSPZV0247SGRW9tIqPjOXZukaIdZyXOIVyVHUts8k(slash)/basic-demo.csv
    row_number: 1
    spreadsheet_url: https://docs.google.com/spreadsheets/d/1kzlSPZV0247SGRW9tIqPjOXZukaIdZyXOIVyVHUts8k/edit#gid=1821235469
    worksheet_name: basic-demo
  server_ip: 192.168.178.21
  server_port: 42143
  use_tb: false
  use_wandb: false
  wandb:
    netrc_path: ~/.netrc
run_locally: true
use_hardcoded_config: false
