delta:fixed_params/exp_group_name: basic-demo
delta:fixed_params/exp_name: long sleep
delta:fixed_params/image/color: green
delta:fixed_params/image/shape: &id001
- 32
- 32
delta:fixed_params/initialization_type: 2
delta:fixed_params/params/random_seed: 5
delta:logging/server_ip: 192.168.212.131
delta:logging/server_port: 54947
delta:run_locally: false
exp_group_name: basic-demo
exp_name: long sleep
fixed_params:
  exp_group_name: basic-demo
  exp_name: long sleep
  image: &id002
    color: green
    shape: *id001
  initialization_type: 2
  params: &id003
    random_seed: 5
image: *id002
initialization_type: 2
logging:
  gdrive_storage_folder: https://drive.google.com/drive/u/0/folders/12_wdaaWk_bCRpEnbO5K8cEWiClDp_mtc
  output_csv:
    path: /mnt/qb/work/oh/owl661/temp_stuned/STAI-tuned-testing/inputs/https:(slash)(slash)docs.google.com(slash)spreadsheets(slash)d(slash)1kzlSPZV0247SGRW9tIqPjOXZukaIdZyXOIVyVHUts8k(slash)/sample-runs-wandb.csv
    row_number: 5
    spreadsheet_url: https://docs.google.com/spreadsheets/d/1kzlSPZV0247SGRW9tIqPjOXZukaIdZyXOIVyVHUts8k/edit#gid=1821235469
    worksheet_name: sample-runs-wandb
  server_ip: 192.168.212.131
  server_port: 54947
  use_tb: false
  use_wandb: true
  wandb:
    netrc_path: ~/.netrc
params: *id003
run_locally: false
use_hardcoded_config: false
